### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by j8r**
- Use `fallback-x11` instead of `x11`
Reference: https://docs.flatpak.org/en/latest/sandbox-permissions.html?highlight=fallback-x11#standard-permissions
- Use `metainfo` instead of `appdata`.
Reference: https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html#spec-appdata-introduction

### CODE REVIEW

**Comment by catsout** [comment]
@j8r 
The `fallback-x11` will force wayland, if waylnd is available on host, which may cause ppsspp refuses to run when it needs xwayland.  
This option is only suitable for apps with fully native wayland support.

**Comment by j8r** [comment]
If PPSSPP does not support Wayland, let's remove its socket permission then.

**Comment by j8r** [comment]
PPSSPP seems to support Wayland - what do you mean by "PPSSPP needs xwayland"?

**Comment by catsout** [comment]
>If PPSSPP does not support Wayland, let's remove its socket permission then.

I don't think we need to remove it, there is no motivation to remove `wayland`.  
Keep `wayland` and `x11` permission to make the ppsspp run into the same behavior like outside flatpak.  
If the future version has better wayland support, we can use `fallback-x11` to get safer

**Comment by catsout** [comment]
> PPSSPP seems to support Wayland - what do you mean by "PPSSPP needs xwayland"?  

It needs xwayland on kde.

**Comment by j8r** [comment]
I can confirm PPSSPP does not work on KDE Wayland. Cannot confirm for GNOME though, Wayland may be broken on it too.

**Pull request merged**
