### PR TITLE
Update to 1.11

### PR DESCRIPTION
**Pull request by catsout**

### CODE REVIEW

**Comment by rlac** [comment]
Build failure should be fixed by https://github.com/hrydgard/ppsspp/issues/14386 (not in a tagged release yet).

**Comment by catsout** [comment]
> Build failure should be fixed by hrydgard/ppsspp#14386 (not in a tagged release yet).

Thanks

**Comment by catsout** [comment]
@joshas @rlac
Could you test this build?

**Comment by catsout** [comment]
No need to test.  
Seems there are already some issues https://github.com/hrydgard/ppsspp/issues/14400 with the miniupnp commit.

**Comment by samy-k97** [comment]
Hey I just want to thank you for doing this. I've been trying to wrap my head around this and you've made it look easy

**Pull request merged**
